# Generated by Django 3.0 on 2020-05-05 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bd', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ips',
            name='intentos',
            field=models.IntegerField(default=0),
        ),
    ]
